Writable:
  LogLevel: INFO
  InsecureSecrets:
    hedgedb:
      SecretName: dbconnection
      SecretData:
        username: hedge
        password: <Only for development, add the generated postgres db pwd in here>

Service:
  Host: localhost
  Port: 48111
  StartupMsg: hedge user application management service started

SecretStore:
  Path: app-hedge-user-app-mgmt/
  TokenFile: /tmp/edgex/secrets/app-hedge-user-app-mgmt/secrets-token.json

MessageBus:
  Disabled: true

Trigger:
  Type: http

ApplicationSettings:
  Usr_db_host: remote-host.domain.com
  Usr_db_port: '5432'
  Usr_db_name: hedge
  Usr_db_user: hedge
  USERNAME: admin
  PLATCRD: xxx
  HTPASSWD_FILE_PATH: /tmp/.htpasswd
  USER_EMAIL: admin@domain.com
  Usr_application_name: hEdge IoT Platform
  #Is_External_Auth: 'true'
  UserId_header: X-Credential-Identifier
  Grafana_Server: 'http://remote-host.domain.com:8000/hedge/hedge-grafana'
  Grafana_Admin: admin
  #Grafana_Pass:
  Grafana_DataSync_Interval_mins: 5m
  Enable_Grafana_sync: 'false'
  Consul_DC_Name: HEDGE_MANAGEMENT
  CONSUL_SERVICES_URL: http://localhost:8500
