// Code generated by mockery v2.38.0. DO NOT EDIT.

package ml_agent

import (
	interfaces "github.com/edgexfoundry/app-functions-sdk-go/v3/pkg/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// MockMqttSender is an autogenerated mock type for the MqttSender type
type MockMqttSender struct {
	mock.Mock
}

type MockMqttSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMqttSender) EXPECT() *MockMqttSender_Expecter {
	return &MockMqttSender_Expecter{mock: &_m.Mock}
}

// MQTTSend provides a mock function with given fields: ctx, data
func (_m *MockMqttSender) MQTTSend(ctx interfaces.AppFunctionContext, data interface{}) (bool, interface{}) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for MQTTSend")
	}

	var r0 bool
	var r1 interface{}
	if rf, ok := ret.Get(0).(func(interfaces.AppFunctionContext, interface{}) (bool, interface{})); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(interfaces.AppFunctionContext, interface{}) bool); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(interfaces.AppFunctionContext, interface{}) interface{}); ok {
		r1 = rf(ctx, data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(interface{})
		}
	}

	return r0, r1
}

// MockMqttSender_MQTTSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MQTTSend'
type MockMqttSender_MQTTSend_Call struct {
	*mock.Call
}

// MQTTSend is a helper method to define mock.On call
//   - ctx interfaces.AppFunctionContext
//   - data interface{}
func (_e *MockMqttSender_Expecter) MQTTSend(ctx interface{}, data interface{}) *MockMqttSender_MQTTSend_Call {
	return &MockMqttSender_MQTTSend_Call{Call: _e.mock.On("MQTTSend", ctx, data)}
}

func (_c *MockMqttSender_MQTTSend_Call) Run(run func(ctx interfaces.AppFunctionContext, data interface{})) *MockMqttSender_MQTTSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interfaces.AppFunctionContext), args[1].(interface{}))
	})
	return _c
}

func (_c *MockMqttSender_MQTTSend_Call) Return(_a0 bool, _a1 interface{}) *MockMqttSender_MQTTSend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMqttSender_MQTTSend_Call) RunAndReturn(run func(interfaces.AppFunctionContext, interface{}) (bool, interface{})) *MockMqttSender_MQTTSend_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMqttSender creates a new instance of MockMqttSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMqttSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMqttSender {
	mock := &MockMqttSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
