#
# Contributors: BMC Helix, Inc.
#
# (c) Copyright 2020-2025 BMC Helix, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

#build stage
# Default values: placeholders to pull latest version for dev, will be overridden from Makefile
ARG GO_BASE=golang:latest
ARG ALPINE_BASE=alpine:latest

FROM ${GO_BASE} AS builder

# Switch to root user for installation
USER root

ARG ALPINE_PKG_BASE="make git"
ARG ALPINE_PKG_EXTRA=""

# RUN sed -e 's/dl-cdn[.]alpinelinux.org/nl.alpinelinux.org/g' -i~ /etc/apk/repositories
RUN apk add --update --no-cache ${ALPINE_PKG_BASE} ${ALPINE_PKG_EXTRA}

# add git for go modules
WORKDIR /hedge
COPY go.mod .

# Not sure what is the purpose here
RUN go mod download all
COPY edge-ml-service edge-ml-service
COPY common common
# Check if the below is reqired or not
#RUN apk info -a zeromq-dev

#create binary file in the container
RUN GO111MODULE=on go build -ldflags "-X hedge.Version=latest" -o hedge-ml-broker ./edge-ml-service/cmd/hedge-ml-broker/main.go

#---------------------------------

#final stage
FROM ${ALPINE_BASE}

# Switch to root user for installation
USER root

# dumb-init is required as security-bootstrapper uses it in the entrypoint script
RUN apk add --update --no-cache ca-certificates dumb-init
#RUN apk --no-cache add zeromq

# Turn off secure mode for examples. Not recommended for production
#ENV EDGEX_SECURITY_SECRET_STORE=false

#COPY --from=builder /app/Attribution.txt /Attribution.txt
#COPY --from=builder /app/LICENSE /LICENSE

# Create a group 'edgex' with GID 2001 and a user 'edgex' with UID 2002
RUN addgroup -S -g 2001 edgex && adduser -S -u 2002 -G edgex edgex

WORKDIR /
# Copy application files and configuration with 'edgex' user and group ownership
COPY --from=builder /hedge/edge-ml-service/cmd/hedge-ml-broker/res /res
COPY --from=builder /hedge/hedge-ml-broker /hedge-ml-broker

RUN chown -R edgex:edgex /res /hedge-ml-broker

RUN mkdir -p /res/edge/models
RUN chmod -R u+rwx /res
RUN chmod u+x /hedge-ml-broker

EXPOSE 48120

# Switch to the non-root 'edgex' user
USER 2002

ENTRYPOINT ["./hedge-ml-broker"]
CMD ["-cp=consul.http://edgex-core-consul:8500", "--registry", "--configDir=./res"]
