name: Run Make on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-make:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up make
      run: sudo apt-get update && sudo apt-get install -y make

#    - name: Set up Golang
#      uses: actions/setup-go@v4
#      with:
#        go-version-file: 'go.mod'
#        cache: true
#
#    - name: Build
#      run: |
#        go mod download all
#
#    - name: Unit Test
#      run: go test ./device-services/...

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: build docker images
      run: make device_virtual

    - name: Push Docker image
      run: |
        IMAGE_NAME=bmchelix/hedge-device-virtual
        docker tag hedge-device-virtual:latest $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
