name: Docker build on merge

on:
    pull_request:
      types: [opened, synchronize, reopened]
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
  contents: write
#on:
#  push:
#    branches:
#      - main  # or your default branch name
#    paths-ignore:
#      - '.hashcache/**'  # Prevent commit loop
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  on-pr-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: build docker images
      run: make docker SERVICE=edgex-services -e IMAGE_PUSH=true

    - name: Commit updated hash files
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        git add .hashcache/
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update hashcache after build [skip ci]"
          git fetch origin "${GITHUB_HEAD_REF}"
          git rebase origin/"${GITHUB_HEAD_REF}"
          git push origin HEAD:"${GITHUB_HEAD_REF}"
        fi

#    - name: Push Docker image
#      run: |
#        IMAGE_NAME=bmchelix/hedge-device-virtual
#        docker tag hedge-device-virtual:latest $IMAGE_NAME:latest
#        docker push $IMAGE_NAME:latest



