name: Run Make on PR

on:
  push:
    branches:
      - main  # or your default branch name
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  on-pr-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: build docker images
      run: make docker SERVICE=hedge-data-enrichment

#    - name: Push Docker image
#      run: |
#        IMAGE_NAME=bmchelix/hedge-device-virtual
#        docker tag hedge-device-virtual:latest $IMAGE_NAME:latest
#        docker push $IMAGE_NAME:latest
